[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/fatih/color"
  version = "1.7.0"

[[constraint]]
  name = "github.com/briandowns/spinner"
  version = "1.4.0"

[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.*"
